# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nifpga_pb2 as nifpga__pb2


class NiFpgaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Open = channel.unary_unary(
                '/nifpga_grpc.NiFpga/Open',
                request_serializer=nifpga__pb2.OpenRequest.SerializeToString,
                response_deserializer=nifpga__pb2.OpenResponse.FromString,
                )
        self.Close = channel.unary_unary(
                '/nifpga_grpc.NiFpga/Close',
                request_serializer=nifpga__pb2.CloseRequest.SerializeToString,
                response_deserializer=nifpga__pb2.CloseResponse.FromString,
                )
        self.Run = channel.unary_unary(
                '/nifpga_grpc.NiFpga/Run',
                request_serializer=nifpga__pb2.RunRequest.SerializeToString,
                response_deserializer=nifpga__pb2.RunResponse.FromString,
                )
        self.Reset = channel.unary_unary(
                '/nifpga_grpc.NiFpga/Reset',
                request_serializer=nifpga__pb2.ResetRequest.SerializeToString,
                response_deserializer=nifpga__pb2.ResetResponse.FromString,
                )
        self.Download = channel.unary_unary(
                '/nifpga_grpc.NiFpga/Download',
                request_serializer=nifpga__pb2.DownloadRequest.SerializeToString,
                response_deserializer=nifpga__pb2.DownloadResponse.FromString,
                )
        self.ReadBool = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadBool',
                request_serializer=nifpga__pb2.ReadBoolRequest.SerializeToString,
                response_deserializer=nifpga__pb2.ReadBoolResponse.FromString,
                )
        self.BeginReadBool = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadBool',
                request_serializer=nifpga__pb2.BeginReadBoolRequest.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadBoolResponse.FromString,
                )
        self.ReadI8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadI8',
                request_serializer=nifpga__pb2.ReadI8Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadI8Response.FromString,
                )
        self.BeginReadI8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadI8',
                request_serializer=nifpga__pb2.BeginReadI8Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadI8Response.FromString,
                )
        self.ReadU8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadU8',
                request_serializer=nifpga__pb2.ReadU8Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadU8Response.FromString,
                )
        self.BeginReadU8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadU8',
                request_serializer=nifpga__pb2.BeginReadU8Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadU8Response.FromString,
                )
        self.ReadI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadI16',
                request_serializer=nifpga__pb2.ReadI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadI16Response.FromString,
                )
        self.BeginReadI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadI16',
                request_serializer=nifpga__pb2.BeginReadI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadI16Response.FromString,
                )
        self.ReadU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadU16',
                request_serializer=nifpga__pb2.ReadU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadU16Response.FromString,
                )
        self.BeginReadU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadU16',
                request_serializer=nifpga__pb2.BeginReadU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadU16Response.FromString,
                )
        self.ReadI32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadI32',
                request_serializer=nifpga__pb2.ReadI32Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadI32Response.FromString,
                )
        self.BeginReadI32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadI32',
                request_serializer=nifpga__pb2.BeginReadI32Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadI32Response.FromString,
                )
        self.ReadU32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadU32',
                request_serializer=nifpga__pb2.ReadU32Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadU32Response.FromString,
                )
        self.BeginReadU32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadU32',
                request_serializer=nifpga__pb2.BeginReadU32Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadU32Response.FromString,
                )
        self.ReadI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadI64',
                request_serializer=nifpga__pb2.ReadI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadI64Response.FromString,
                )
        self.BeginReadI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadI64',
                request_serializer=nifpga__pb2.BeginReadI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadI64Response.FromString,
                )
        self.ReadU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadU64',
                request_serializer=nifpga__pb2.ReadU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadU64Response.FromString,
                )
        self.BeginReadU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadU64',
                request_serializer=nifpga__pb2.BeginReadU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadU64Response.FromString,
                )
        self.WriteBool = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteBool',
                request_serializer=nifpga__pb2.WriteBoolRequest.SerializeToString,
                response_deserializer=nifpga__pb2.WriteBoolResponse.FromString,
                )
        self.BeginWriteBool = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteBool',
                request_serializer=nifpga__pb2.BeginWriteBoolRequest.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteBoolResponse.FromString,
                )
        self.WriteI8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteI8',
                request_serializer=nifpga__pb2.WriteI8Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteI8Response.FromString,
                )
        self.BeginWriteI8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteI8',
                request_serializer=nifpga__pb2.BeginWriteI8Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteI8Response.FromString,
                )
        self.WriteU8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteU8',
                request_serializer=nifpga__pb2.WriteU8Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteU8Response.FromString,
                )
        self.BeginWriteU8 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteU8',
                request_serializer=nifpga__pb2.BeginWriteU8Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteU8Response.FromString,
                )
        self.WriteI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteI16',
                request_serializer=nifpga__pb2.WriteI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteI16Response.FromString,
                )
        self.BeginWriteI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteI16',
                request_serializer=nifpga__pb2.BeginWriteI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteI16Response.FromString,
                )
        self.WriteU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteU16',
                request_serializer=nifpga__pb2.WriteU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteU16Response.FromString,
                )
        self.BeginWriteU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteU16',
                request_serializer=nifpga__pb2.BeginWriteU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteU16Response.FromString,
                )
        self.WriteI32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteI32',
                request_serializer=nifpga__pb2.WriteI32Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteI32Response.FromString,
                )
        self.BeginWriteI32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteI32',
                request_serializer=nifpga__pb2.BeginWriteI32Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteI32Response.FromString,
                )
        self.WriteU32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteU32',
                request_serializer=nifpga__pb2.WriteU32Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteU32Response.FromString,
                )
        self.BeginWriteU32 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteU32',
                request_serializer=nifpga__pb2.BeginWriteU32Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteU32Response.FromString,
                )
        self.WriteI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteI64',
                request_serializer=nifpga__pb2.WriteI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteI64Response.FromString,
                )
        self.BeginWriteI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteI64',
                request_serializer=nifpga__pb2.BeginWriteI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteI64Response.FromString,
                )
        self.WriteU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteU64',
                request_serializer=nifpga__pb2.WriteU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteU64Response.FromString,
                )
        self.BeginWriteU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteU64',
                request_serializer=nifpga__pb2.BeginWriteU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteU64Response.FromString,
                )
        self.ReadArrayI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadArrayI16',
                request_serializer=nifpga__pb2.ReadArrayI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadArrayI16Response.FromString,
                )
        self.BeginReadArrayI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadArrayI16',
                request_serializer=nifpga__pb2.BeginReadArrayI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadArrayI16Response.FromString,
                )
        self.ReadArrayU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadArrayU16',
                request_serializer=nifpga__pb2.ReadArrayU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadArrayU16Response.FromString,
                )
        self.BeginReadArrayU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadArrayU16',
                request_serializer=nifpga__pb2.BeginReadArrayU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadArrayU16Response.FromString,
                )
        self.ReadArrayI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadArrayI64',
                request_serializer=nifpga__pb2.ReadArrayI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadArrayI64Response.FromString,
                )
        self.BeginReadArrayI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadArrayI64',
                request_serializer=nifpga__pb2.BeginReadArrayI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadArrayI64Response.FromString,
                )
        self.ReadArrayU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/ReadArrayU64',
                request_serializer=nifpga__pb2.ReadArrayU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.ReadArrayU64Response.FromString,
                )
        self.BeginReadArrayU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginReadArrayU64',
                request_serializer=nifpga__pb2.BeginReadArrayU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginReadArrayU64Response.FromString,
                )
        self.WriteArrayI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteArrayI16',
                request_serializer=nifpga__pb2.WriteArrayI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteArrayI16Response.FromString,
                )
        self.BeginWriteArrayI16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteArrayI16',
                request_serializer=nifpga__pb2.BeginWriteArrayI16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteArrayI16Response.FromString,
                )
        self.WriteArrayU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteArrayU16',
                request_serializer=nifpga__pb2.WriteArrayU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteArrayU16Response.FromString,
                )
        self.BeginWriteArrayU16 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteArrayU16',
                request_serializer=nifpga__pb2.BeginWriteArrayU16Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteArrayU16Response.FromString,
                )
        self.WriteArrayI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteArrayI64',
                request_serializer=nifpga__pb2.WriteArrayI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteArrayI64Response.FromString,
                )
        self.BeginWriteArrayI64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteArrayI64',
                request_serializer=nifpga__pb2.BeginWriteArrayI64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteArrayI64Response.FromString,
                )
        self.WriteArrayU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/WriteArrayU64',
                request_serializer=nifpga__pb2.WriteArrayU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.WriteArrayU64Response.FromString,
                )
        self.BeginWriteArrayU64 = channel.unary_unary(
                '/nifpga_grpc.NiFpga/BeginWriteArrayU64',
                request_serializer=nifpga__pb2.BeginWriteArrayU64Request.SerializeToString,
                response_deserializer=nifpga__pb2.BeginWriteArrayU64Response.FromString,
                )


class NiFpgaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadBool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadI8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadI8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadU8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadU8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadI32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadI32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadU32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadU32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteBool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteBool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteI8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteI8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteU8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteU8(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteI32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteI32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteU32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteU32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArrayI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadArrayI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArrayU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadArrayU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArrayI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadArrayI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadArrayU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginReadArrayU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteArrayI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteArrayI16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteArrayU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteArrayU16(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteArrayI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteArrayI64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteArrayU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginWriteArrayU64(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NiFpgaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=nifpga__pb2.OpenRequest.FromString,
                    response_serializer=nifpga__pb2.OpenResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=nifpga__pb2.CloseRequest.FromString,
                    response_serializer=nifpga__pb2.CloseResponse.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=nifpga__pb2.RunRequest.FromString,
                    response_serializer=nifpga__pb2.RunResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=nifpga__pb2.ResetRequest.FromString,
                    response_serializer=nifpga__pb2.ResetResponse.SerializeToString,
            ),
            'Download': grpc.unary_unary_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=nifpga__pb2.DownloadRequest.FromString,
                    response_serializer=nifpga__pb2.DownloadResponse.SerializeToString,
            ),
            'ReadBool': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBool,
                    request_deserializer=nifpga__pb2.ReadBoolRequest.FromString,
                    response_serializer=nifpga__pb2.ReadBoolResponse.SerializeToString,
            ),
            'BeginReadBool': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadBool,
                    request_deserializer=nifpga__pb2.BeginReadBoolRequest.FromString,
                    response_serializer=nifpga__pb2.BeginReadBoolResponse.SerializeToString,
            ),
            'ReadI8': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadI8,
                    request_deserializer=nifpga__pb2.ReadI8Request.FromString,
                    response_serializer=nifpga__pb2.ReadI8Response.SerializeToString,
            ),
            'BeginReadI8': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadI8,
                    request_deserializer=nifpga__pb2.BeginReadI8Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadI8Response.SerializeToString,
            ),
            'ReadU8': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadU8,
                    request_deserializer=nifpga__pb2.ReadU8Request.FromString,
                    response_serializer=nifpga__pb2.ReadU8Response.SerializeToString,
            ),
            'BeginReadU8': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadU8,
                    request_deserializer=nifpga__pb2.BeginReadU8Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadU8Response.SerializeToString,
            ),
            'ReadI16': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadI16,
                    request_deserializer=nifpga__pb2.ReadI16Request.FromString,
                    response_serializer=nifpga__pb2.ReadI16Response.SerializeToString,
            ),
            'BeginReadI16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadI16,
                    request_deserializer=nifpga__pb2.BeginReadI16Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadI16Response.SerializeToString,
            ),
            'ReadU16': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadU16,
                    request_deserializer=nifpga__pb2.ReadU16Request.FromString,
                    response_serializer=nifpga__pb2.ReadU16Response.SerializeToString,
            ),
            'BeginReadU16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadU16,
                    request_deserializer=nifpga__pb2.BeginReadU16Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadU16Response.SerializeToString,
            ),
            'ReadI32': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadI32,
                    request_deserializer=nifpga__pb2.ReadI32Request.FromString,
                    response_serializer=nifpga__pb2.ReadI32Response.SerializeToString,
            ),
            'BeginReadI32': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadI32,
                    request_deserializer=nifpga__pb2.BeginReadI32Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadI32Response.SerializeToString,
            ),
            'ReadU32': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadU32,
                    request_deserializer=nifpga__pb2.ReadU32Request.FromString,
                    response_serializer=nifpga__pb2.ReadU32Response.SerializeToString,
            ),
            'BeginReadU32': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadU32,
                    request_deserializer=nifpga__pb2.BeginReadU32Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadU32Response.SerializeToString,
            ),
            'ReadI64': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadI64,
                    request_deserializer=nifpga__pb2.ReadI64Request.FromString,
                    response_serializer=nifpga__pb2.ReadI64Response.SerializeToString,
            ),
            'BeginReadI64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadI64,
                    request_deserializer=nifpga__pb2.BeginReadI64Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadI64Response.SerializeToString,
            ),
            'ReadU64': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadU64,
                    request_deserializer=nifpga__pb2.ReadU64Request.FromString,
                    response_serializer=nifpga__pb2.ReadU64Response.SerializeToString,
            ),
            'BeginReadU64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadU64,
                    request_deserializer=nifpga__pb2.BeginReadU64Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadU64Response.SerializeToString,
            ),
            'WriteBool': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteBool,
                    request_deserializer=nifpga__pb2.WriteBoolRequest.FromString,
                    response_serializer=nifpga__pb2.WriteBoolResponse.SerializeToString,
            ),
            'BeginWriteBool': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteBool,
                    request_deserializer=nifpga__pb2.BeginWriteBoolRequest.FromString,
                    response_serializer=nifpga__pb2.BeginWriteBoolResponse.SerializeToString,
            ),
            'WriteI8': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteI8,
                    request_deserializer=nifpga__pb2.WriteI8Request.FromString,
                    response_serializer=nifpga__pb2.WriteI8Response.SerializeToString,
            ),
            'BeginWriteI8': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteI8,
                    request_deserializer=nifpga__pb2.BeginWriteI8Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteI8Response.SerializeToString,
            ),
            'WriteU8': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteU8,
                    request_deserializer=nifpga__pb2.WriteU8Request.FromString,
                    response_serializer=nifpga__pb2.WriteU8Response.SerializeToString,
            ),
            'BeginWriteU8': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteU8,
                    request_deserializer=nifpga__pb2.BeginWriteU8Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteU8Response.SerializeToString,
            ),
            'WriteI16': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteI16,
                    request_deserializer=nifpga__pb2.WriteI16Request.FromString,
                    response_serializer=nifpga__pb2.WriteI16Response.SerializeToString,
            ),
            'BeginWriteI16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteI16,
                    request_deserializer=nifpga__pb2.BeginWriteI16Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteI16Response.SerializeToString,
            ),
            'WriteU16': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteU16,
                    request_deserializer=nifpga__pb2.WriteU16Request.FromString,
                    response_serializer=nifpga__pb2.WriteU16Response.SerializeToString,
            ),
            'BeginWriteU16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteU16,
                    request_deserializer=nifpga__pb2.BeginWriteU16Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteU16Response.SerializeToString,
            ),
            'WriteI32': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteI32,
                    request_deserializer=nifpga__pb2.WriteI32Request.FromString,
                    response_serializer=nifpga__pb2.WriteI32Response.SerializeToString,
            ),
            'BeginWriteI32': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteI32,
                    request_deserializer=nifpga__pb2.BeginWriteI32Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteI32Response.SerializeToString,
            ),
            'WriteU32': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteU32,
                    request_deserializer=nifpga__pb2.WriteU32Request.FromString,
                    response_serializer=nifpga__pb2.WriteU32Response.SerializeToString,
            ),
            'BeginWriteU32': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteU32,
                    request_deserializer=nifpga__pb2.BeginWriteU32Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteU32Response.SerializeToString,
            ),
            'WriteI64': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteI64,
                    request_deserializer=nifpga__pb2.WriteI64Request.FromString,
                    response_serializer=nifpga__pb2.WriteI64Response.SerializeToString,
            ),
            'BeginWriteI64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteI64,
                    request_deserializer=nifpga__pb2.BeginWriteI64Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteI64Response.SerializeToString,
            ),
            'WriteU64': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteU64,
                    request_deserializer=nifpga__pb2.WriteU64Request.FromString,
                    response_serializer=nifpga__pb2.WriteU64Response.SerializeToString,
            ),
            'BeginWriteU64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteU64,
                    request_deserializer=nifpga__pb2.BeginWriteU64Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteU64Response.SerializeToString,
            ),
            'ReadArrayI16': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArrayI16,
                    request_deserializer=nifpga__pb2.ReadArrayI16Request.FromString,
                    response_serializer=nifpga__pb2.ReadArrayI16Response.SerializeToString,
            ),
            'BeginReadArrayI16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadArrayI16,
                    request_deserializer=nifpga__pb2.BeginReadArrayI16Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadArrayI16Response.SerializeToString,
            ),
            'ReadArrayU16': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArrayU16,
                    request_deserializer=nifpga__pb2.ReadArrayU16Request.FromString,
                    response_serializer=nifpga__pb2.ReadArrayU16Response.SerializeToString,
            ),
            'BeginReadArrayU16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadArrayU16,
                    request_deserializer=nifpga__pb2.BeginReadArrayU16Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadArrayU16Response.SerializeToString,
            ),
            'ReadArrayI64': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArrayI64,
                    request_deserializer=nifpga__pb2.ReadArrayI64Request.FromString,
                    response_serializer=nifpga__pb2.ReadArrayI64Response.SerializeToString,
            ),
            'BeginReadArrayI64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadArrayI64,
                    request_deserializer=nifpga__pb2.BeginReadArrayI64Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadArrayI64Response.SerializeToString,
            ),
            'ReadArrayU64': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArrayU64,
                    request_deserializer=nifpga__pb2.ReadArrayU64Request.FromString,
                    response_serializer=nifpga__pb2.ReadArrayU64Response.SerializeToString,
            ),
            'BeginReadArrayU64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginReadArrayU64,
                    request_deserializer=nifpga__pb2.BeginReadArrayU64Request.FromString,
                    response_serializer=nifpga__pb2.BeginReadArrayU64Response.SerializeToString,
            ),
            'WriteArrayI16': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteArrayI16,
                    request_deserializer=nifpga__pb2.WriteArrayI16Request.FromString,
                    response_serializer=nifpga__pb2.WriteArrayI16Response.SerializeToString,
            ),
            'BeginWriteArrayI16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteArrayI16,
                    request_deserializer=nifpga__pb2.BeginWriteArrayI16Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteArrayI16Response.SerializeToString,
            ),
            'WriteArrayU16': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteArrayU16,
                    request_deserializer=nifpga__pb2.WriteArrayU16Request.FromString,
                    response_serializer=nifpga__pb2.WriteArrayU16Response.SerializeToString,
            ),
            'BeginWriteArrayU16': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteArrayU16,
                    request_deserializer=nifpga__pb2.BeginWriteArrayU16Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteArrayU16Response.SerializeToString,
            ),
            'WriteArrayI64': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteArrayI64,
                    request_deserializer=nifpga__pb2.WriteArrayI64Request.FromString,
                    response_serializer=nifpga__pb2.WriteArrayI64Response.SerializeToString,
            ),
            'BeginWriteArrayI64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteArrayI64,
                    request_deserializer=nifpga__pb2.BeginWriteArrayI64Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteArrayI64Response.SerializeToString,
            ),
            'WriteArrayU64': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteArrayU64,
                    request_deserializer=nifpga__pb2.WriteArrayU64Request.FromString,
                    response_serializer=nifpga__pb2.WriteArrayU64Response.SerializeToString,
            ),
            'BeginWriteArrayU64': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginWriteArrayU64,
                    request_deserializer=nifpga__pb2.BeginWriteArrayU64Request.FromString,
                    response_serializer=nifpga__pb2.BeginWriteArrayU64Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nifpga_grpc.NiFpga', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NiFpga(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/Open',
            nifpga__pb2.OpenRequest.SerializeToString,
            nifpga__pb2.OpenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/Close',
            nifpga__pb2.CloseRequest.SerializeToString,
            nifpga__pb2.CloseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/Run',
            nifpga__pb2.RunRequest.SerializeToString,
            nifpga__pb2.RunResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/Reset',
            nifpga__pb2.ResetRequest.SerializeToString,
            nifpga__pb2.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/Download',
            nifpga__pb2.DownloadRequest.SerializeToString,
            nifpga__pb2.DownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadBool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadBool',
            nifpga__pb2.ReadBoolRequest.SerializeToString,
            nifpga__pb2.ReadBoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadBool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadBool',
            nifpga__pb2.BeginReadBoolRequest.SerializeToString,
            nifpga__pb2.BeginReadBoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadI8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadI8',
            nifpga__pb2.ReadI8Request.SerializeToString,
            nifpga__pb2.ReadI8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadI8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadI8',
            nifpga__pb2.BeginReadI8Request.SerializeToString,
            nifpga__pb2.BeginReadI8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadU8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadU8',
            nifpga__pb2.ReadU8Request.SerializeToString,
            nifpga__pb2.ReadU8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadU8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadU8',
            nifpga__pb2.BeginReadU8Request.SerializeToString,
            nifpga__pb2.BeginReadU8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadI16',
            nifpga__pb2.ReadI16Request.SerializeToString,
            nifpga__pb2.ReadI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadI16',
            nifpga__pb2.BeginReadI16Request.SerializeToString,
            nifpga__pb2.BeginReadI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadU16',
            nifpga__pb2.ReadU16Request.SerializeToString,
            nifpga__pb2.ReadU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadU16',
            nifpga__pb2.BeginReadU16Request.SerializeToString,
            nifpga__pb2.BeginReadU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadI32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadI32',
            nifpga__pb2.ReadI32Request.SerializeToString,
            nifpga__pb2.ReadI32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadI32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadI32',
            nifpga__pb2.BeginReadI32Request.SerializeToString,
            nifpga__pb2.BeginReadI32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadU32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadU32',
            nifpga__pb2.ReadU32Request.SerializeToString,
            nifpga__pb2.ReadU32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadU32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadU32',
            nifpga__pb2.BeginReadU32Request.SerializeToString,
            nifpga__pb2.BeginReadU32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadI64',
            nifpga__pb2.ReadI64Request.SerializeToString,
            nifpga__pb2.ReadI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadI64',
            nifpga__pb2.BeginReadI64Request.SerializeToString,
            nifpga__pb2.BeginReadI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadU64',
            nifpga__pb2.ReadU64Request.SerializeToString,
            nifpga__pb2.ReadU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadU64',
            nifpga__pb2.BeginReadU64Request.SerializeToString,
            nifpga__pb2.BeginReadU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteBool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteBool',
            nifpga__pb2.WriteBoolRequest.SerializeToString,
            nifpga__pb2.WriteBoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteBool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteBool',
            nifpga__pb2.BeginWriteBoolRequest.SerializeToString,
            nifpga__pb2.BeginWriteBoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteI8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteI8',
            nifpga__pb2.WriteI8Request.SerializeToString,
            nifpga__pb2.WriteI8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteI8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteI8',
            nifpga__pb2.BeginWriteI8Request.SerializeToString,
            nifpga__pb2.BeginWriteI8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteU8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteU8',
            nifpga__pb2.WriteU8Request.SerializeToString,
            nifpga__pb2.WriteU8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteU8(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteU8',
            nifpga__pb2.BeginWriteU8Request.SerializeToString,
            nifpga__pb2.BeginWriteU8Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteI16',
            nifpga__pb2.WriteI16Request.SerializeToString,
            nifpga__pb2.WriteI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteI16',
            nifpga__pb2.BeginWriteI16Request.SerializeToString,
            nifpga__pb2.BeginWriteI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteU16',
            nifpga__pb2.WriteU16Request.SerializeToString,
            nifpga__pb2.WriteU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteU16',
            nifpga__pb2.BeginWriteU16Request.SerializeToString,
            nifpga__pb2.BeginWriteU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteI32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteI32',
            nifpga__pb2.WriteI32Request.SerializeToString,
            nifpga__pb2.WriteI32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteI32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteI32',
            nifpga__pb2.BeginWriteI32Request.SerializeToString,
            nifpga__pb2.BeginWriteI32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteU32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteU32',
            nifpga__pb2.WriteU32Request.SerializeToString,
            nifpga__pb2.WriteU32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteU32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteU32',
            nifpga__pb2.BeginWriteU32Request.SerializeToString,
            nifpga__pb2.BeginWriteU32Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteI64',
            nifpga__pb2.WriteI64Request.SerializeToString,
            nifpga__pb2.WriteI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteI64',
            nifpga__pb2.BeginWriteI64Request.SerializeToString,
            nifpga__pb2.BeginWriteI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteU64',
            nifpga__pb2.WriteU64Request.SerializeToString,
            nifpga__pb2.WriteU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteU64',
            nifpga__pb2.BeginWriteU64Request.SerializeToString,
            nifpga__pb2.BeginWriteU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadArrayI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadArrayI16',
            nifpga__pb2.ReadArrayI16Request.SerializeToString,
            nifpga__pb2.ReadArrayI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadArrayI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadArrayI16',
            nifpga__pb2.BeginReadArrayI16Request.SerializeToString,
            nifpga__pb2.BeginReadArrayI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadArrayU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadArrayU16',
            nifpga__pb2.ReadArrayU16Request.SerializeToString,
            nifpga__pb2.ReadArrayU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadArrayU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadArrayU16',
            nifpga__pb2.BeginReadArrayU16Request.SerializeToString,
            nifpga__pb2.BeginReadArrayU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadArrayI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadArrayI64',
            nifpga__pb2.ReadArrayI64Request.SerializeToString,
            nifpga__pb2.ReadArrayI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadArrayI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadArrayI64',
            nifpga__pb2.BeginReadArrayI64Request.SerializeToString,
            nifpga__pb2.BeginReadArrayI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadArrayU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/ReadArrayU64',
            nifpga__pb2.ReadArrayU64Request.SerializeToString,
            nifpga__pb2.ReadArrayU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginReadArrayU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginReadArrayU64',
            nifpga__pb2.BeginReadArrayU64Request.SerializeToString,
            nifpga__pb2.BeginReadArrayU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteArrayI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteArrayI16',
            nifpga__pb2.WriteArrayI16Request.SerializeToString,
            nifpga__pb2.WriteArrayI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteArrayI16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteArrayI16',
            nifpga__pb2.BeginWriteArrayI16Request.SerializeToString,
            nifpga__pb2.BeginWriteArrayI16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteArrayU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteArrayU16',
            nifpga__pb2.WriteArrayU16Request.SerializeToString,
            nifpga__pb2.WriteArrayU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteArrayU16(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteArrayU16',
            nifpga__pb2.BeginWriteArrayU16Request.SerializeToString,
            nifpga__pb2.BeginWriteArrayU16Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteArrayI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteArrayI64',
            nifpga__pb2.WriteArrayI64Request.SerializeToString,
            nifpga__pb2.WriteArrayI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteArrayI64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteArrayI64',
            nifpga__pb2.BeginWriteArrayI64Request.SerializeToString,
            nifpga__pb2.BeginWriteArrayI64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteArrayU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/WriteArrayU64',
            nifpga__pb2.WriteArrayU64Request.SerializeToString,
            nifpga__pb2.WriteArrayU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BeginWriteArrayU64(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nifpga_grpc.NiFpga/BeginWriteArrayU64',
            nifpga__pb2.BeginWriteArrayU64Request.SerializeToString,
            nifpga__pb2.BeginWriteArrayU64Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
