# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\rnidevice_grpc\"2\n\x07Session\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12\x0c\n\x02id\x18\x02 \x01(\rH\x00\x42\t\n\x07session\"V\n\x10\x44\x65viceProperties\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0e\n\x06vendor\x18\x03 \x01(\t\x12\x15\n\rserial_number\x18\x04 \x01(\t\"\x19\n\x17\x45numerateDevicesRequest\"L\n\x18\x45numerateDevicesResponse\x12\x30\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x1f.nidevice_grpc.DeviceProperties\";\n\x0eReserveRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"&\n\x0fReserveResponse\x12\x13\n\x0bis_reserved\x18\x01 \x01(\x08\"F\n\x19IsReservedByClientRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"1\n\x1aIsReservedByClientResponse\x12\x13\n\x0bis_reserved\x18\x01 \x01(\x08\"=\n\x10UnreserveRequest\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"*\n\x11UnreserveResponse\x12\x15\n\ris_unreserved\x18\x01 \x01(\x08\"\x14\n\x12ResetServerRequest\".\n\x13ResetServerResponse\x12\x17\n\x0fis_server_reset\x18\x01 \x01(\x08\x32\xd2\x03\n\x10SessionUtilities\x12\x63\n\x10\x45numerateDevices\x12&.nidevice_grpc.EnumerateDevicesRequest\x1a\'.nidevice_grpc.EnumerateDevicesResponse\x12H\n\x07Reserve\x12\x1d.nidevice_grpc.ReserveRequest\x1a\x1e.nidevice_grpc.ReserveResponse\x12i\n\x12IsReservedByClient\x12(.nidevice_grpc.IsReservedByClientRequest\x1a).nidevice_grpc.IsReservedByClientResponse\x12N\n\tUnreserve\x12\x1f.nidevice_grpc.UnreserveRequest\x1a .nidevice_grpc.UnreserveResponse\x12T\n\x0bResetServer\x12!.nidevice_grpc.ResetServerRequest\x1a\".nidevice_grpc.ResetServerResponseBB\n\x12\x63om.ni.grpc.deviceB\x08NiDeviceP\x01\xaa\x02\x1fNationalInstruments.Grpc.Deviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.ni.grpc.deviceB\010NiDeviceP\001\252\002\037NationalInstruments.Grpc.Device'
  _globals['_SESSION']._serialized_start=32
  _globals['_SESSION']._serialized_end=82
  _globals['_DEVICEPROPERTIES']._serialized_start=84
  _globals['_DEVICEPROPERTIES']._serialized_end=170
  _globals['_ENUMERATEDEVICESREQUEST']._serialized_start=172
  _globals['_ENUMERATEDEVICESREQUEST']._serialized_end=197
  _globals['_ENUMERATEDEVICESRESPONSE']._serialized_start=199
  _globals['_ENUMERATEDEVICESRESPONSE']._serialized_end=275
  _globals['_RESERVEREQUEST']._serialized_start=277
  _globals['_RESERVEREQUEST']._serialized_end=336
  _globals['_RESERVERESPONSE']._serialized_start=338
  _globals['_RESERVERESPONSE']._serialized_end=376
  _globals['_ISRESERVEDBYCLIENTREQUEST']._serialized_start=378
  _globals['_ISRESERVEDBYCLIENTREQUEST']._serialized_end=448
  _globals['_ISRESERVEDBYCLIENTRESPONSE']._serialized_start=450
  _globals['_ISRESERVEDBYCLIENTRESPONSE']._serialized_end=499
  _globals['_UNRESERVEREQUEST']._serialized_start=501
  _globals['_UNRESERVEREQUEST']._serialized_end=562
  _globals['_UNRESERVERESPONSE']._serialized_start=564
  _globals['_UNRESERVERESPONSE']._serialized_end=606
  _globals['_RESETSERVERREQUEST']._serialized_start=608
  _globals['_RESETSERVERREQUEST']._serialized_end=628
  _globals['_RESETSERVERRESPONSE']._serialized_start=630
  _globals['_RESETSERVERRESPONSE']._serialized_end=676
  _globals['_SESSIONUTILITIES']._serialized_start=679
  _globals['_SESSIONUTILITIES']._serialized_end=1145
# @@protoc_insertion_point(module_scope)
